version: "3.7"
services:
  wordpress:
    image: yannis76/prod-web:0.0.1
    container_name: wordpress-prod
    ports:
      - "8083:80"
    environment:
      WORDPRESS_DB_HOST: client1-sql
      WORDPRESS_DB_USER: client1-wordpress
      WORDPRESS_DB_PASSWORD: cesi
      WORDPRESS_DB_NAME: client1-wordpress
