services:
  bdd:
    container_name: client1-sql
    image: mariadb:lts
    restart: always
    environment: 
      MARIADB_ROOT_PASSWORD: cesi
    networks:
      - client1-network
    volumes:
      - client1-volbdd:/var/lib/mysql/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    networks:
    - client1-network
    
  wordpress:
    depends_on:
    - bdd
    container_name: client1-wordpress
    image: wordpress:latest
    ports:
    - "8081:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: client1-sql
      WORDPRESS_DB_USER: client1-wordpress
      WORDPRESS_DB_PASSWORD: cesi
      WORDPRESS_DB_NAME: client1-wordpress
    networks:
    - client1-network
    volumes:
    - client1-volweb:/var/www/html

networks:
  client1-network:
    driver: bridge

volumes:
  client1-volbdd:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:/Users/ourag/Desktop/DockerWordPress/bdd
  client1-volweb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: C:/Users/ourag/Desktop/DockerWordPress/web

